# Site settings
title: Touch the Invisible
subtitle: Bridging Physical and Digital Modeling of Biological Macromolecules
email: shinwookim@pitt.edu
description: > # this means to ignore newlines until "baseurl:"
  A University of Pittsburgh Research Project.
baseurl: "/invisible" # the subpath of your site, e.g. /blog
url: "shinwookim.github.io" # the base hostname & protocol for your site
twitter_username: PittTweet
github_username:  shinwookim

# Build settings
markdown: kramdown
permalink: pretty
